/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IKukuSwapLocker } from "../IKukuSwapLocker";

export class IKukuSwapLocker__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKukuSwapLocker {
    return new Contract(address, _abi, signerOrProvider) as IKukuSwapLocker;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_lpToken",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_unlock_date",
        type: "uint256",
      },
      {
        internalType: "bool",
        name: "_fee_in_eth",
        type: "bool",
      },
      {
        internalType: "address payable",
        name: "_withdrawer",
        type: "address",
      },
    ],
    name: "lockLPToken",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];
