/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IKukuSwapStaking } from "../IKukuSwapStaking";

export class IKukuSwapStaking__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKukuSwapStaking {
    return new Contract(address, _abi, signerOrProvider) as IKukuSwapStaking;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        internalType: "bool",
        name: "isAuth",
        type: "bool",
      },
    ],
    name: "authorize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
