/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IKukuSwapPresaleFactory } from "../IKukuSwapPresaleFactory";

export class IKukuSwapPresaleFactory__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IKukuSwapPresaleFactory {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IKukuSwapPresaleFactory;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_presaleAddress",
        type: "address",
      },
    ],
    name: "presaleIsRegistered",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_presaleAddress",
        type: "address",
      },
    ],
    name: "registerPresale",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];
