/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface KukuSwapPresaleFactoryInterface extends ethers.utils.Interface {
  functions: {
    "adminAllowPresaleGenerator(address,bool)": FunctionFragment;
    "initialize()": FunctionFragment;
    "owner()": FunctionFragment;
    "presaleAtIndex(uint256)": FunctionFragment;
    "presaleAtIndexByUser(address,uint256)": FunctionFragment;
    "presaleGeneratorAtIndex(uint256)": FunctionFragment;
    "presaleGeneratorsLength()": FunctionFragment;
    "presaleIsRegistered(address)": FunctionFragment;
    "presalesLength()": FunctionFragment;
    "presalesLengthByUser(address)": FunctionFragment;
    "registerPresale(address,address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "adminAllowPresaleGenerator",
    values: [string, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "presaleAtIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "presaleAtIndexByUser",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "presaleGeneratorAtIndex",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "presaleGeneratorsLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "presaleIsRegistered",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "presalesLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "presalesLengthByUser",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerPresale",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "adminAllowPresaleGenerator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "presaleAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "presaleAtIndexByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "presaleGeneratorAtIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "presaleGeneratorsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "presaleIsRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "presalesLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "presalesLengthByUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerPresale",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "presaleRegistered(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "presaleRegistered"): EventFragment;
}

export class KukuSwapPresaleFactory extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: KukuSwapPresaleFactoryInterface;

  functions: {
    adminAllowPresaleGenerator(
      _address: string,
      _allow: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "adminAllowPresaleGenerator(address,bool)"(
      _address: string,
      _allow: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    initialize(overrides?: Overrides): Promise<ContractTransaction>;

    "initialize()"(overrides?: Overrides): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    presaleAtIndex(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "presaleAtIndex(uint256)"(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    presaleAtIndexByUser(
      _owner: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "presaleAtIndexByUser(address,uint256)"(
      _owner: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    presaleGeneratorAtIndex(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "presaleGeneratorAtIndex(uint256)"(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    presaleGeneratorsLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    "presaleGeneratorsLength()"(
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    presaleIsRegistered(
      _presaleAddress: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    "presaleIsRegistered(address)"(
      _presaleAddress: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    presalesLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    "presalesLength()"(overrides?: CallOverrides): Promise<[BigNumber]>;

    presalesLengthByUser(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "presalesLengthByUser(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    registerPresale(
      _presaleAddress: string,
      _presaleOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "registerPresale(address,address)"(
      _presaleAddress: string,
      _presaleOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  adminAllowPresaleGenerator(
    _address: string,
    _allow: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "adminAllowPresaleGenerator(address,bool)"(
    _address: string,
    _allow: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  initialize(overrides?: Overrides): Promise<ContractTransaction>;

  "initialize()"(overrides?: Overrides): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  presaleAtIndex(
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "presaleAtIndex(uint256)"(
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  presaleAtIndexByUser(
    _owner: string,
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "presaleAtIndexByUser(address,uint256)"(
    _owner: string,
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  presaleGeneratorAtIndex(
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "presaleGeneratorAtIndex(uint256)"(
    _index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  presaleGeneratorsLength(overrides?: CallOverrides): Promise<BigNumber>;

  "presaleGeneratorsLength()"(overrides?: CallOverrides): Promise<BigNumber>;

  presaleIsRegistered(
    _presaleAddress: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  "presaleIsRegistered(address)"(
    _presaleAddress: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  presalesLength(overrides?: CallOverrides): Promise<BigNumber>;

  "presalesLength()"(overrides?: CallOverrides): Promise<BigNumber>;

  presalesLengthByUser(
    _owner: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "presalesLengthByUser(address)"(
    _owner: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  registerPresale(
    _presaleAddress: string,
    _presaleOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "registerPresale(address,address)"(
    _presaleAddress: string,
    _presaleOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    adminAllowPresaleGenerator(
      _address: string,
      _allow: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "adminAllowPresaleGenerator(address,bool)"(
      _address: string,
      _allow: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    initialize(overrides?: CallOverrides): Promise<void>;

    "initialize()"(overrides?: CallOverrides): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    presaleAtIndex(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "presaleAtIndex(uint256)"(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    presaleAtIndexByUser(
      _owner: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "presaleAtIndexByUser(address,uint256)"(
      _owner: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    presaleGeneratorAtIndex(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "presaleGeneratorAtIndex(uint256)"(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    presaleGeneratorsLength(overrides?: CallOverrides): Promise<BigNumber>;

    "presaleGeneratorsLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    presaleIsRegistered(
      _presaleAddress: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "presaleIsRegistered(address)"(
      _presaleAddress: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    presalesLength(overrides?: CallOverrides): Promise<BigNumber>;

    "presalesLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    presalesLengthByUser(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "presalesLengthByUser(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerPresale(
      _presaleAddress: string,
      _presaleOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "registerPresale(address,address)"(
      _presaleAddress: string,
      _presaleOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;

    presaleRegistered(presaleContract: null): EventFilter;
  };

  estimateGas: {
    adminAllowPresaleGenerator(
      _address: string,
      _allow: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "adminAllowPresaleGenerator(address,bool)"(
      _address: string,
      _allow: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    initialize(overrides?: Overrides): Promise<BigNumber>;

    "initialize()"(overrides?: Overrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    presaleAtIndex(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "presaleAtIndex(uint256)"(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    presaleAtIndexByUser(
      _owner: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "presaleAtIndexByUser(address,uint256)"(
      _owner: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    presaleGeneratorAtIndex(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "presaleGeneratorAtIndex(uint256)"(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    presaleGeneratorsLength(overrides?: CallOverrides): Promise<BigNumber>;

    "presaleGeneratorsLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    presaleIsRegistered(
      _presaleAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "presaleIsRegistered(address)"(
      _presaleAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    presalesLength(overrides?: CallOverrides): Promise<BigNumber>;

    "presalesLength()"(overrides?: CallOverrides): Promise<BigNumber>;

    presalesLengthByUser(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "presalesLengthByUser(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    registerPresale(
      _presaleAddress: string,
      _presaleOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "registerPresale(address,address)"(
      _presaleAddress: string,
      _presaleOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    adminAllowPresaleGenerator(
      _address: string,
      _allow: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "adminAllowPresaleGenerator(address,bool)"(
      _address: string,
      _allow: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    initialize(overrides?: Overrides): Promise<PopulatedTransaction>;

    "initialize()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    presaleAtIndex(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "presaleAtIndex(uint256)"(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    presaleAtIndexByUser(
      _owner: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "presaleAtIndexByUser(address,uint256)"(
      _owner: string,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    presaleGeneratorAtIndex(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "presaleGeneratorAtIndex(uint256)"(
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    presaleGeneratorsLength(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "presaleGeneratorsLength()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    presaleIsRegistered(
      _presaleAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "presaleIsRegistered(address)"(
      _presaleAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    presalesLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "presalesLength()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    presalesLengthByUser(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "presalesLengthByUser(address)"(
      _owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    registerPresale(
      _presaleAddress: string,
      _presaleOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "registerPresale(address,address)"(
      _presaleAddress: string,
      _presaleOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
