/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IKukuSwapStakingInterface extends ethers.utils.Interface {
  functions: {
    "authorize(address,bool)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "authorize",
    values: [string, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "authorize", data: BytesLike): Result;

  events: {};
}

export class IKukuSwapStaking extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IKukuSwapStakingInterface;

  functions: {
    authorize(
      _user: string,
      isAuth: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "authorize(address,bool)"(
      _user: string,
      isAuth: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  authorize(
    _user: string,
    isAuth: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "authorize(address,bool)"(
    _user: string,
    isAuth: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    authorize(
      _user: string,
      isAuth: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    "authorize(address,bool)"(
      _user: string,
      isAuth: boolean,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    authorize(
      _user: string,
      isAuth: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "authorize(address,bool)"(
      _user: string,
      isAuth: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    authorize(
      _user: string,
      isAuth: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "authorize(address,bool)"(
      _user: string,
      isAuth: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
